file = open("Bucket-List.txt", "w")
file.write("1.Visit The Eiffel Tower\n")
file.write("2.Learn to play the guitar\n")
file.write("3.Code my own game\n")
file.close()
print("Bucket List saved to Bucket-List.txt!")

file = open("Bucket-List.txt", "r")
content = file.read()
print("\n=== MY Bucket List ===")
print(content)
file.close()

file = open("Bucket-List.txt", "r")
lines = file.readlines()
print(f"You have {len(lines)} items in your bucket list.")  
file.close()

file = open("Bucket-List.txt", "a")
file.write("4.Travel to Japan\n")
file.write("5. Run a 5K Marathon\n")
file.close()
print("\n2 more items added")

file = open("Bucket-List.txt", "r")
print("\n=== UPDATED Bucket List ===")
print(file.read())
file.close()